micronaut:
  application:
    name: micronautguide
---
#tag::mongodb[]
mongodb:
  uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017
  #uri: mongodb://user:password@${MONGO_HOST:mongo1}:${MONGO_PORT:27017}/test
#end::mongodb[]
---
#tag::db[]
db:
  name: 'test'
  collection: 'fruit'
#end::db[]
